### ISSUE TITLE
Normalizing Shift Scores

### ISSUE THREAD

**Issue by cvanoort** [ryanjgallagher/shifterator#7]
In Shift.get_shift_scores the default behavior is to normalize the shift scores to have a sum of 1 (normalization is applied [here](https://github.com/ryanjgallagher/shifterator/blob/103880e02604447ba2f0cac26d1717e86ac2ff8a/shifterator/shifterator.py#L239)). However, it is possible to have shift scores that sum to 0. Should we skip the normalization in this case, or is there a principled way that we can fix the normalization?

Here's an example that highlights the issue:
```python
system_1 = {"A": 10, "B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 10}
system_2 = {"B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 10, "H": 10}

shift = EntropyShift(system_1, system_2)
shift.get_shift_graph()
```

All types besides A and H have a shift score of 0. A and H have equal magnitude shift scores with opposing signs, so when we get to the normalization step a division by 0 error occurs.

**Comment by cvanoort** [comment]
Since the shift scores can be negative, it might make sense to normalize by the sum of the absolute values of the shift scores?

**Comment by ryanjgallagher** [comment]
Yeah that's a good observation. Something similar happens for just doing a proportion shift, which is why I put the normalize flag there, but it's less natural to just turn that off for the entropy one.

The sum of the absolute values I think makes sense, but it's also different than the norm that Chris and Peter use on their shifts. Maybe this is a good thing to bring up and ask about in the Slack channel for if there's a reason they use the total score rather than the sum of the absolute values as the normalization?

**Comment by ryanjgallagher** [comment]
I changed the code to use the sum of absolute values as the normalization instead of the just the raw sum. It's more reliable for these edge cases, and I also think it's easier to interpret.

Thanks for pointing this out @cvanoort!
